Adding support for the values comming from the OM2M devices
Greg8978/toaster pull request #48
Opened 2016-09-21 13:00 UTC by dkurzaj

Adds the support of the IoT devices represented in OM2M. The facts deducted are only valuable for the specified devices and conditions.

2016-09-21 13:45 UTC, Greg8978 commented on pdg/src/OM2MObjectReader.cpp
> +    curObject->setTime(milli_sec);
I think usually we have time in microseconds in TOASTER.

2016-09-21 13:54 UTC, Greg8978 commented on pdg/src/main.cpp
> +                                fact_msg.property = "FanOFF";
The property should be the same: FanON, only the value should change.

2016-09-21 14:01 UTC, Greg8978 requested changes
The code is good and thank you for corrections outside of your contribution :)

This being said, I'm not very satisfied with the part checking which IOT object it is.

Couldn't we have xml file to associate the element to the fact generation?
There is an example here (https://github.com/Greg8978/hatm/blob/master/data/list_nodes.xml), where I associated task names to there speech, you can use the same idea to associate object name to a property...

Something like

for each IOTObject{
  property = loadPropertyFromXml(objectID))
  Value = value.c_str()
}

Also the property should not change, only the value.
e.g
property = FanOn | value = true (fan is on) 
property = FanOn | value = false (fan is off)
property = LightColor  | value = yellow (color is yellow)

...

Let me know if you need to discuss further about that :)

2016-09-21 14:04 UTC, Greg8978 commented
I forgot but the advantage of the xml here is also to add IOT object without need of recompiling pdg :)

2016-09-22 13:21 UTC, Greg8978 approved these changes

2016-09-22 13:24 UTC, Greg8978 commented
If you can update the wiki (maybe create IOT page with a link in pdg page?)
to explain how to use pdg with IOT objects and how to edit the xml to add IOTobjects/facts it would be perfect :)

Cheers!

2016-09-22 13:25 UTC, merged

2016-09-22 13:44 UTC, dkurzaj commented
Okay sure !